# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from db_tools.proto import db_tools_pb2 as db__tools__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in db_tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DbToolsServiceStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NearbyTrips = channel.unary_unary(
                '/db_tools.DbToolsService/NearbyTrips',
                request_serializer=db__tools__pb2.NearbyTripsRequest.SerializeToString,
                response_deserializer=db__tools__pb2.NearbyTripsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/db_tools.DbToolsService/HealthCheck',
                request_serializer=db__tools__pb2.Empty.SerializeToString,
                response_deserializer=db__tools__pb2.HealthResponse.FromString,
                _registered_method=True)


class DbToolsServiceServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def NearbyTrips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DbToolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NearbyTrips': grpc.unary_unary_rpc_method_handler(
                    servicer.NearbyTrips,
                    request_deserializer=db__tools__pb2.NearbyTripsRequest.FromString,
                    response_serializer=db__tools__pb2.NearbyTripsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=db__tools__pb2.Empty.FromString,
                    response_serializer=db__tools__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'db_tools.DbToolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('db_tools.DbToolsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DbToolsService(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def NearbyTrips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_tools.DbToolsService/NearbyTrips',
            db__tools__pb2.NearbyTripsRequest.SerializeToString,
            db__tools__pb2.NearbyTripsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/db_tools.DbToolsService/HealthCheck',
            db__tools__pb2.Empty.SerializeToString,
            db__tools__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
