# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: db_tools.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'db_tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x62_tools.proto\x12\x08\x64\x62_tools\"\x07\n\x05\x45mpty\"^\n\x12NearbyTripsRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x10\n\x08radius_m\x18\x03 \x01(\x01\x12\x0e\n\x06starts\x18\x04 \x01(\x08\x12\x0c\n\x04\x65psg\x18\x05 \x01(\x05\"\x97\x03\n\x10NearbyTripResult\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x10\n\x08route_id\x18\x02 \x01(\t\x12\x15\n\rtrip_headsign\x18\x03 \x01(\t\x12\x18\n\x10trip_headsign_ar\x18\x04 \x01(\t\x12\x14\n\x0c\x64irection_id\x18\x05 \x01(\x05\x12\x18\n\x10route_short_name\x18\x06 \x01(\t\x12\x1b\n\x13route_short_name_ar\x18\x07 \x01(\t\x12\x12\n\nroute_name\x18\x08 \x01(\t\x12\x15\n\rroute_name_ar\x18\t \x01(\t\x12\x12\n\ndistance_m\x18\n \x01(\x01\x12\x17\n\x0f\x63losest_stop_id\x18\x0b \x01(\t\x12\x19\n\x11\x63losest_stop_name\x18\x0c \x01(\t\x12\x1c\n\x14\x63losest_stop_name_ar\x18\r \x01(\t\x12\x18\n\x10\x63losest_stop_lat\x18\x0e \x01(\x01\x12\x18\n\x10\x63losest_stop_lon\x18\x0f \x01(\x01\x12\x1d\n\x15\x63losest_stop_sequence\x18\x10 \x01(\x05\"\x99\x01\n\x13NearbyTripsResponse\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x10\n\x08radius_m\x18\x03 \x01(\x01\x12\x0e\n\x06starts\x18\x04 \x01(\x08\x12\x0c\n\x04\x65psg\x18\x05 \x01(\x05\x12\r\n\x05\x63ount\x18\x06 \x01(\x05\x12)\n\x05trips\x18\x07 \x03(\x0b\x32\x1a.db_tools.NearbyTripResult\"6\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x62_connected\x18\x02 \x01(\x08\x32\x96\x01\n\x0e\x44\x62ToolsService\x12J\n\x0bNearbyTrips\x12\x1c.db_tools.NearbyTripsRequest\x1a\x1d.db_tools.NearbyTripsResponse\x12\x38\n\x0bHealthCheck\x12\x0f.db_tools.Empty\x1a\x18.db_tools.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'db_tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_NEARBYTRIPSREQUEST']._serialized_start=37
  _globals['_NEARBYTRIPSREQUEST']._serialized_end=131
  _globals['_NEARBYTRIPRESULT']._serialized_start=134
  _globals['_NEARBYTRIPRESULT']._serialized_end=541
  _globals['_NEARBYTRIPSRESPONSE']._serialized_start=544
  _globals['_NEARBYTRIPSRESPONSE']._serialized_end=697
  _globals['_HEALTHRESPONSE']._serialized_start=699
  _globals['_HEALTHRESPONSE']._serialized_end=753
  _globals['_DBTOOLSSERVICE']._serialized_start=756
  _globals['_DBTOOLSSERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
