# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from traffic_updater.proto import traffic_pb2 as traffic__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in traffic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrafficUpdateServiceStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerUpdate = channel.unary_unary(
                '/traffic.TrafficUpdateService/TriggerUpdate',
                request_serializer=traffic__pb2.TriggerRequest.SerializeToString,
                response_deserializer=traffic__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/traffic.TrafficUpdateService/GetStatus',
                request_serializer=traffic__pb2.Empty.SerializeToString,
                response_deserializer=traffic__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateTrip = channel.unary_unary(
                '/traffic.TrafficUpdateService/UpdateTrip',
                request_serializer=traffic__pb2.UpdateTripRequest.SerializeToString,
                response_deserializer=traffic__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.StreetTraffic = channel.unary_unary(
                '/traffic.TrafficUpdateService/StreetTraffic',
                request_serializer=traffic__pb2.StreetTrafficRequest.SerializeToString,
                response_deserializer=traffic__pb2.StreetTrafficResponse.FromString,
                _registered_method=True)
        self.ListStreets = channel.unary_unary(
                '/traffic.TrafficUpdateService/ListStreets',
                request_serializer=traffic__pb2.Empty.SerializeToString,
                response_deserializer=traffic__pb2.StreetListResponse.FromString,
                _registered_method=True)


class TrafficUpdateServiceServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def TriggerUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreetTraffic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStreets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerUpdate,
                    request_deserializer=traffic__pb2.TriggerRequest.FromString,
                    response_serializer=traffic__pb2.UpdateResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=traffic__pb2.Empty.FromString,
                    response_serializer=traffic__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTrip,
                    request_deserializer=traffic__pb2.UpdateTripRequest.FromString,
                    response_serializer=traffic__pb2.UpdateResponse.SerializeToString,
            ),
            'StreetTraffic': grpc.unary_unary_rpc_method_handler(
                    servicer.StreetTraffic,
                    request_deserializer=traffic__pb2.StreetTrafficRequest.FromString,
                    response_serializer=traffic__pb2.StreetTrafficResponse.SerializeToString,
            ),
            'ListStreets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStreets,
                    request_deserializer=traffic__pb2.Empty.FromString,
                    response_serializer=traffic__pb2.StreetListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'traffic.TrafficUpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('traffic.TrafficUpdateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrafficUpdateService(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def TriggerUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.TrafficUpdateService/TriggerUpdate',
            traffic__pb2.TriggerRequest.SerializeToString,
            traffic__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.TrafficUpdateService/GetStatus',
            traffic__pb2.Empty.SerializeToString,
            traffic__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.TrafficUpdateService/UpdateTrip',
            traffic__pb2.UpdateTripRequest.SerializeToString,
            traffic__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreetTraffic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.TrafficUpdateService/StreetTraffic',
            traffic__pb2.StreetTrafficRequest.SerializeToString,
            traffic__pb2.StreetTrafficResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStreets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/traffic.TrafficUpdateService/ListStreets',
            traffic__pb2.Empty.SerializeToString,
            traffic__pb2.StreetListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
