# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from geocoding_api.proto import geocoding_pb2 as geocoding__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geocoding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeocodingServiceStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Geocode = channel.unary_unary(
                '/geocoding.GeocodingService/Geocode',
                request_serializer=geocoding__pb2.GeocodeRequest.SerializeToString,
                response_deserializer=geocoding__pb2.GeocodeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/geocoding.GeocodingService/HealthCheck',
                request_serializer=geocoding__pb2.Empty.SerializeToString,
                response_deserializer=geocoding__pb2.HealthResponse.FromString,
                _registered_method=True)


class GeocodingServiceServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def Geocode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeocodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Geocode': grpc.unary_unary_rpc_method_handler(
                    servicer.Geocode,
                    request_deserializer=geocoding__pb2.GeocodeRequest.FromString,
                    response_serializer=geocoding__pb2.GeocodeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=geocoding__pb2.Empty.FromString,
                    response_serializer=geocoding__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geocoding.GeocodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geocoding.GeocodingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeocodingService(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Geocode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geocoding.GeocodingService/Geocode',
            geocoding__pb2.GeocodeRequest.SerializeToString,
            geocoding__pb2.GeocodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geocoding.GeocodingService/HealthCheck',
            geocoding__pb2.Empty.SerializeToString,
            geocoding__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
