# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geocoding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'geocoding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgeocoding.proto\x12\tgeocoding\"\x07\n\x05\x45mpty\"e\n\x0eGeocodeRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04\x62ias\x18\x03 \x01(\x08\x12\x10\n\x08user_lat\x18\x04 \x01(\x01\x12\x10\n\x08user_lng\x18\x05 \x01(\x01\"O\n\rGeocodeResult\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x19\n\x11\x66ormatted_address\x18\x03 \x01(\t\"\x9a\x01\n\x0fGeocodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05query\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0c\n\x04\x62ias\x18\x04 \x01(\x08\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x12)\n\x07results\x18\x06 \x03(\x0b\x32\x18.geocoding.GeocodeResult\x12\r\n\x05\x65rror\x18\x07 \x01(\t\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x90\x01\n\x10GeocodingService\x12@\n\x07Geocode\x12\x19.geocoding.GeocodeRequest\x1a\x1a.geocoding.GeocodeResponse\x12:\n\x0bHealthCheck\x12\x10.geocoding.Empty\x1a\x19.geocoding.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geocoding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_GEOCODEREQUEST']._serialized_start=39
  _globals['_GEOCODEREQUEST']._serialized_end=140
  _globals['_GEOCODERESULT']._serialized_start=142
  _globals['_GEOCODERESULT']._serialized_end=221
  _globals['_GEOCODERESPONSE']._serialized_start=224
  _globals['_GEOCODERESPONSE']._serialized_end=378
  _globals['_HEALTHRESPONSE']._serialized_start=380
  _globals['_HEALTHRESPONSE']._serialized_end=412
  _globals['_GEOCODINGSERVICE']._serialized_start=415
  _globals['_GEOCODINGSERVICE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
